version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.forgerock.openbanking:forgerock-openbanking-model
    versions:
    - 1.0.87
    - 1.0.88
    - 1.0.89
    - 1.1.0
    - 1.1.2
  - dependency-name: com.forgerock.openbanking.clients:forgerock-openbanking-analytics-client
    versions:
    - 1.1.0
    - 1.1.2
  - dependency-name: org.apache.maven.plugins:maven-release-plugin
    versions:
    - 3.0.0-M4
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
  - dependency-name: com.forgerock.openbanking.aspsp:forgerock-openbanking-uk-aspsp-common
    versions:
    - 1.0.114
    - 1.0.116
    - 1.1.117
    - 1.2.1
    - 1.2.2
